import {
  EmitContext,
  emitFile,
  listServices,
  getNamespaceFullName,
  navigateTypesInNamespace,
  Model,
  Namespace,
  Interface,
  Program,
  Type,
  Scalar,
} from "@typespec/compiler";

export type EmitterOptions = {
  "emitter-output-dir": string;
};

interface FieldInfo {
  name: string;
  type: Type;
  optional: boolean;
}

interface ServiceInfo {
  namespace: Namespace;
  iface: Interface;
  serviceName: string;
  serviceFQN: string;
  models: Model[];
}

function extractFields(model: Model): FieldInfo[] {
  const fields: FieldInfo[] = [];
  for (const [name, prop] of model.properties) {
    fields.push({ name, type: prop.type, optional: prop.optional ?? false });
  }
  return fields;
}

function isStringType(type: Type): boolean {
  if (type.kind === "Scalar") return (type as Scalar).name === "string";
  if (type.kind === "Intrinsic") return (type as any).name === "string";
  return false;
}

function isIntType(type: Type): boolean {
  if (type.kind === "Scalar") {
    const n = (type as Scalar).name;
    return ["int8","int16","int32","int64","uint8","uint16","uint32","uint64","integer"].includes(n);
  }
  return false;
}

function isFloatType(type: Type): boolean {
  if (type.kind === "Scalar") {
    const n = (type as Scalar).name;
    return ["float","float32","float64","decimal"].includes(n);
  }
  return false;
}

function isBoolType(type: Type): boolean {
  if (type.kind === "Scalar") return (type as Scalar).name === "boolean";
  return false;
}

function isArrayType(type: Type): boolean {
  return type.kind === "Model" && !!(type as Model).indexer;
}

function arrayElementType(type: Type): Type {
  if (type.kind === "Model" && (type as Model).indexer) return (type as Model).indexer!.value;
  return type;
}

function typeToKotlin(type: Type): string {
  if (isStringType(type)) return "String";
  if (type.kind === "Scalar") {
    const n = (type as Scalar).name;
    if (n === "int8") return "Byte";
    if (n === "int16") return "Short";
    if (n === "int32") return "Int";
    if (n === "int64") return "Long";
    if (n === "uint8") return "UByte";
    if (n === "uint16") return "UShort";
    if (n === "uint32") return "UInt";
    if (n === "uint64") return "ULong";
    if (n === "float32") return "Float";
    if (n === "float64") return "Double";
    if (n === "boolean") return "Boolean";
  }
  if (isFloatType(type)) return "Double";
  if (isArrayType(type)) return `List<${typeToKotlin(arrayElementType(type))}>`;
  if (type.kind === "Model") return type.name || "Any";
  return "Any";
}

function collectServices(program: Program): ServiceInfo[] {
  const services = listServices(program);
  const result: ServiceInfo[] = [];
  function collectFromNs(ns: Namespace) {
    for (const [,iface] of ns.interfaces) {
      const nsFQN = getNamespaceFullName(ns);
      const models: Model[] = [];
      const seen = new Set<string>();
      navigateTypesInNamespace(ns, { model: (m: Model) => { if (m.name && !seen.has(m.name)) { models.push(m); seen.add(m.name); } } });
      result.push({ namespace: ns, iface, serviceName: iface.name, serviceFQN: `${nsFQN}.${iface.name}`, models });
    }
  }
  for (const svc of services) collectFromNs(svc.type);
  if (result.length === 0) {
    const globalNs = program.getGlobalNamespaceType();
    for (const [, ns] of globalNs.namespaces) collectFromNs(ns);
    collectFromNs(globalNs);
  }
  return result;
}

export async function $onEmit(context: EmitContext<EmitterOptions>) {
  const program = context.program;
  const outputDir = context.emitterOutputDir;
  const services = collectServices(program);
  for (const svc of services) {
    const toSnake = (s: string) => s.replace(/([A-Z])/g, (m, c, i) => (i ? "_" : "") + c.toLowerCase());
    const pkg = toSnake(svc.namespace.name?.toLowerCase() ?? "svc");
    const lines: string[] = [];
    lines.push("// Generated by @specodec/typespec-specodec-kotlin. DO NOT EDIT.");
    lines.push(`package ${pkg}`);
    lines.push("import specodec.*");
    lines.push("");
    for (const m of svc.models) {
      if (!m.name) continue;
      const fields = extractFields(m);
      lines.push(`data class ${m.name}(`);
      for (let i = 0; i < fields.length; i++) {
        const f = fields[i];
        const ktType = typeToKotlin(f.type);
        const nullable = f.optional ? "?" : "";
        const comma = i < fields.length - 1 ? "," : "";
        lines.push(`    val ${f.name}: ${ktType}${nullable}${comma}`);
      }
      lines.push(")");
      lines.push("");
    }
    const fileName = toSnake(svc.serviceName) + "_types.kt";
    await emitFile(program, { path: `${outputDir}/${fileName}`, content: lines.join("\n") });
  }
}
